variables:
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  DOCKER_USERNAME: $DOCKER_USERNAME
  FEED_API: udagram-api-feed
  USER_API: udagram-api-user
  FRONTEND: udagram-frontend
  REVERSE_PROXY: reverseproxy

build-push-docker-image-job:
  # Specify a Docker image to run the job in.
  image: docker:latest
  # Specify an additional image 'docker:dind' ("Docker-in-Docker") that
  # will start up the Docker daemon when it is brought up by a runner.
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker tag udagram-api-feed abedaliby/udagram-api-feed:v1
    - docker push abedaliby/udagram-api-feed 