variables:
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  DOCKER_USERNAME: $DOCKER_USERNAME
  FEED_API: udagram-api-feed
  USER_API: udagram-api-user
  FRONTEND: udagram-frontend
  REVERSE_PROXY: reverseproxy

build-push-docker-image-job:
  # Specify a Docker image to run the job in.
  image: docker:latest
  # Specify an additional image 'docker:dind' ("Docker-in-Docker") that
  # will start up the Docker daemon when it is brought up by a runner.
  services:
    - docker:dind
  before_script:
    # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    # feed
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker tag udagram-api-feed abedaliby/udagram-api-feed
    - docker push abedaliby/udagram-api-feed
    # user
    - docker build -t udagram-api-user ./udagram-api-user
    - docker tag udagram-api-user abedaliby/udagram-api-user
    - docker push abedaliby/udagram-api-user
    # frontend
    - docker build -t udagram-frontend ./udagram-frontend
    - docker tag udagram-frontend abedaliby/udagram-frontend
    - docker push abedaliby/udagram-frontend
    # reverseproxy
    - docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - docker tag udagram-reverseproxy abedaliby/udagram-reverseproxy
    - docker push abedaliby/udagram-reverseproxy